name: Deploy Admin Panel to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy Admin Panel
    if: github.repository == 'KaviLabs/Asantravels_AdminPanal'
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Prepare Admin Files
        run: |
          mkdir dist
          cp admin.php dist/ || true
          cp admin.html dist/ || true
          cp admin_bookings.php dist/ || true
          cp asn_Gallery.php dist/ || true
          cp asn_galary.php dist/ || true
          cp asn_Bookings.php dist/ || true
          cp asn_Contact.php dist/ || true
          cp asn_Reviews.php dist/ || true
          cp asn_subscribers.php dist/ || true
          cp asn_custom_admin.php dist/ || true
          cp asn_admin_loging.php dist/ || true
          cp custom_admin.php dist/ || true
          cp custom_admin_old.php dist/ || true
          cp logout.php dist/ || true

      - name: 📂 Sync files (Admin Panel Only)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ADMIN_FTP_SERVER }}
          username: ${{ secrets.ADMIN_FTP_USERNAME }}
          password: ${{ secrets.ADMIN_FTP_PASSWORD }}
          local-dir: dist/
          server-dir: htdocs/
